# Generated by Django 3.2.8 on 2021-10-26 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paintapp', '0002_user_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintapp.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintapp.user')),
            ],
            options={
                'unique_together': {('room', 'x', 'y')},
            },
        ),
    ]
