# Generated by Django 3.2.8 on 2021-10-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintapp', '0004_user_room_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_room',
            name='color',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
