# Generated by Django 3.2.8 on 2021-10-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintapp', '0005_alter_user_room_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_room',
            name='color',
            field=models.CharField(max_length=7),
        ),
    ]
